const day = 24 * 60 * 60 * 1000;

export const coupons = [
  {
    code: "WELCOME10",
    description: "10% off your first order, up to ₹500",
    type: "percent",
    value: 10,
    minOrder: 499,
    maxDiscount: 500,
    perUserLimit: 1,
    expiresAt: null,
  },
  {
    code: "FLAT200",
    description: "Flat ₹200 off on orders above ₹1,999",
    type: "flat",
    value: 200,
    minOrder: 1999,
    maxDiscount: null,
    perUserLimit: 3,
    expiresAt: null,
  },
  {
    code: "FESTIVE25",
    description: "25% off festive picks, up to ₹1,500",
    type: "percent",
    value: 25,
    minOrder: 2999,
    maxDiscount: 1500,
    perUserLimit: 2,
    usageLimit: 500,
    expiresAt: new Date(Date.now() + 45 * day),
  },
  {
    code: "FREESHIP",
    description: "Free standard shipping on any order",
    type: "free_shipping",
    value: 0,
    minOrder: 0,
    maxDiscount: null,
    perUserLimit: 5,
    expiresAt: null,
  },
  {
    code: "OLD50",
    description: "Expired: 50% off (for testing)",
    type: "percent",
    value: 50,
    minOrder: 0,
    maxDiscount: 1000,
    perUserLimit: 1,
    expiresAt: new Date(Date.now() - 10 * day),
  },
] as const;
