import { axis, img, matrix, SIZES, type SeedProduct } from "./helpers";

const stock = ({ size }: Record<string, string>) => (size === "XL" ? 6 : size === "M" ? 30 : 18);

export const fashionMen: SeedProduct[] = [
  {
    title: "Oversized Heavyweight Tee",
    brand: "Loom & Co",
    category: "mens-topwear",
    description: "A 240 GSM combed-cotton tee with a dropped shoulder and a boxy cut that keeps its shape wash after wash.",
    highlights: ["240 GSM combed cotton", "Boxy, dropped-shoulder fit", "Pre-shrunk", "Ribbed collar"],
    specs: { Fabric: "100% cotton", Fit: "Oversized", Sleeve: "Half", Care: "Machine wash cold" },
    images: [img("photo-1521572163474-6864f9cf17ab"), img("photo-1583743814966-8936f5b7be1a"), img("photo-1618354691373-d851c5c3a990")],
    variantAxes: ["color", "size"],
    variants: matrix("TSHOVS", [["color", ["Black", "Ecru", "Olive"]], ["size", SIZES]], 899, 1499, stock),
    tags: ["tshirt", "oversized", "bestseller"],
    isFeatured: true,
  },
  {
    title: "Linen Resort Shirt",
    brand: "Loom & Co",
    category: "mens-topwear",
    description: "Breathable European linen with a relaxed collar, built for humid afternoons.",
    highlights: ["100% linen", "Relaxed collar", "Coconut-shell buttons"],
    specs: { Fabric: "100% linen", Fit: "Relaxed", Sleeve: "Half" },
    images: [img("photo-1596755094514-f87e34085b2c"), img("photo-1602810318383-e386cc2a3ccf")],
    variantAxes: ["color", "size"],
    variants: matrix("LINRES", [["color", ["Sand", "Sky"]], ["size", SIZES]], 1799, 2999, stock),
    tags: ["shirt", "linen", "summer"],
  },
  {
    title: "Merino Crewneck Sweater",
    brand: "Northloft",
    category: "mens-topwear",
    description: "Extra-fine merino that regulates temperature, resists odour and layers under anything.",
    highlights: ["Extra-fine merino", "Itch-free", "Machine washable"],
    specs: { Fabric: "100% merino wool", Fit: "Regular", Weight: "Midweight" },
    images: [img("photo-1620799140408-edc6dcb6d633"), img("photo-1614975059251-992f11792b9f")],
    variantAxes: ["color", "size"],
    variants: matrix("MERCRW", [["color", ["Charcoal", "Rust"]], ["size", ["M", "L", "XL"]]], 3499, 4999, stock),
    tags: ["sweater", "winter"],
  },
  {
    title: "Everyday Puffer Jacket",
    brand: "Northloft",
    category: "mens-topwear",
    description: "A packable puffer with recycled insulation and a water-repellent shell that folds into its own pocket.",
    highlights: ["Recycled insulation", "Packable", "DWR shell", "Hidden zip pockets"],
    specs: { Shell: "Recycled nylon", Insulation: "Synthetic", Fit: "Regular" },
    images: [img("photo-1551028719-00167b16eac5"), img("photo-1539533018447-63fcce2678e3")],
    variantAxes: ["color", "size"],
    variants: matrix("PUFFER", [["color", ["Black", "Forest"]], ["size", SIZES]], 3999, 6999, stock),
    tags: ["jacket", "winter"],
    isDeal: true,
  },
  {
    title: "Slim Tapered Stretch Jeans",
    brand: "Denim Republic",
    category: "mens-bottomwear",
    description: "Mid-rise, slim through the thigh and tapered at the ankle, with 2% stretch that moves with you.",
    highlights: ["2% stretch denim", "Mid rise", "Tapered leg", "Reinforced belt loops"],
    specs: { Fabric: "98% cotton, 2% elastane", Fit: "Slim tapered", Rise: "Mid", Wash: "Indigo" },
    images: [img("photo-1542272604-787c3835535d"), img("photo-1541099649105-f69ad21f3246"), img("photo-1475178626620-a4d074967452")],
    variantAxes: ["wash", "waist"],
    variants: matrix("JNSSLM", [["wash", ["Dark Indigo", "Light Wash"]], ["waist", ["30", "32", "34", "36"]]], 2199, 3499),
    tags: ["jeans", "denim", "bestseller"],
    isFeatured: true,
  },
  {
    title: "Tech Chino Trousers",
    brand: "Denim Republic",
    category: "mens-bottomwear",
    description: "Four-way stretch chinos with a hidden zip pocket and a crease that stays put after a 12-hour day.",
    highlights: ["4-way stretch", "Wrinkle resistant", "Hidden zip pocket"],
    specs: { Fabric: "Cotton-nylon blend", Fit: "Slim", Rise: "Mid" },
    images: [img("photo-1473966968600-fa801b869a1a"), img("photo-1624378439575-d8705ad7ae80")],
    variantAxes: ["color", "waist"],
    variants: matrix("CHINO", [["color", ["Khaki", "Navy"]], ["waist", ["30", "32", "34"]]], 1899, 2999),
    tags: ["chinos", "office"],
  },
  {
    title: "Relaxed Cargo Joggers",
    brand: "Loom & Co",
    category: "mens-bottomwear",
    description: "Soft French-terry joggers with utility pockets and an elasticated cuff.",
    highlights: ["French terry", "6 pockets", "Elasticated cuff"],
    specs: { Fabric: "80% cotton, 20% polyester", Fit: "Relaxed" },
    images: [img("photo-1552902865-b72c031ac5ea"), img("photo-1552374196-1ab2a1c593e8")],
    variantAxes: ["size"],
    variants: axis("CARGOJ", "size", SIZES, 1499, 2499, [20, 30, 25, 5]),
    tags: ["joggers", "athleisure"],
  },
  {
    title: "Chikankari Kurta Set",
    brand: "Roohani",
    category: "mens-ethnic",
    description: "Hand-embroidered Lucknowi chikankari on breathable cotton, paired with matching straight-cut pyjamas.",
    highlights: ["Hand-embroidered", "100% cotton", "Kurta + pyjama set", "Festive ready"],
    specs: { Fabric: "Cotton", Work: "Chikankari", Length: "Knee length", Occasion: "Festive" },
    images: [img("photo-1583391733956-3750e0ff4e8b"), img("photo-1597983073493-88cd35cf93b0")],
    variantAxes: ["color", "size"],
    variants: matrix("KURTA", [["color", ["Ivory", "Mint", "Mustard"]], ["size", SIZES]], 2499, 4499, stock),
    tags: ["kurta", "ethnic", "festive"],
    isFeatured: true,
  },
  {
    title: "Bandhgala Nehru Jacket",
    brand: "Roohani",
    category: "mens-ethnic",
    description: "A structured jacquard Nehru jacket that dresses up any kurta or shirt.",
    highlights: ["Jacquard weave", "Structured shoulders", "Full lining"],
    specs: { Fabric: "Polyester jacquard", Fit: "Slim", Closure: "Buttons" },
    images: [img("photo-1617137968427-85924c800a22"), img("photo-1583391733956-3750e0ff4e8b")],
    variantAxes: ["color", "size"],
    variants: matrix("NEHRU", [["color", ["Maroon", "Teal"]], ["size", ["M", "L", "XL"]]], 2999, 4999, stock),
    tags: ["nehru jacket", "wedding"],
  },
];
