import { axis, img, matrix, single, SIZES, type SeedProduct } from "./helpers";

const stock = ({ size }: Record<string, string>) => (size === "S" ? 28 : size === "XL" ? 7 : 20);

export const fashionWomen: SeedProduct[] = [
  {
    title: "Floral Wrap Midi Dress",
    brand: "Mira",
    category: "womens-dresses",
    description: "A fluid viscose wrap dress with a flattering V-neck, fluted sleeves and a print painted in-house.",
    highlights: ["Hand-painted print", "Adjustable wrap tie", "Fluted sleeves", "Midi length"],
    specs: { Fabric: "100% viscose", Length: "Midi", Sleeve: "3/4", Occasion: "Brunch, day out" },
    images: [img("photo-1595777457583-95e059d581b8"), img("photo-1572804013309-59a88b7e92f1"), img("photo-1496747611176-843222e1e57c")],
    variantAxes: ["color", "size"],
    variants: matrix("WRAPMD", [["color", ["Terracotta", "Indigo"]], ["size", SIZES]], 2299, 3999, stock),
    tags: ["dress", "floral", "bestseller"],
    isFeatured: true,
  },
  {
    title: "Satin Slip Dress",
    brand: "Mira",
    category: "womens-dresses",
    description: "Bias-cut satin that skims rather than clings, with adjustable straps and a cowl neck.",
    highlights: ["Bias cut", "Adjustable straps", "Cowl neckline"],
    specs: { Fabric: "Polyester satin", Length: "Midi", Fit: "Slim" },
    images: [img("photo-1566174053879-31528523f8ae"), img("photo-1539008835657-9e8e9680c956")],
    variantAxes: ["color", "size"],
    variants: matrix("SLIPDR", [["color", ["Champagne", "Emerald", "Black"]], ["size", ["S", "M", "L"]]], 1999, 3499, stock),
    tags: ["dress", "party"],
  },
  {
    title: "Tiered Cotton Maxi Dress",
    brand: "Sundara",
    category: "womens-dresses",
    description: "Three breezy tiers of mul cotton with pockets, because every dress should have pockets.",
    highlights: ["Mul cotton", "Side pockets", "Smocked back"],
    specs: { Fabric: "100% cotton", Length: "Maxi", Fit: "Relaxed" },
    images: [img("photo-1515372039744-b8f02a3ae446"), img("photo-1612336307429-8a898d10e223")],
    variantAxes: ["color", "size"],
    variants: matrix("TIERMX", [["color", ["Lemon", "Lilac"]], ["size", SIZES]], 1799, 2999, stock),
    tags: ["dress", "summer", "cotton"],
    isDeal: true,
  },
  {
    title: "Banarasi Silk Saree",
    brand: "Sundara",
    category: "womens-ethnic",
    description: "Handwoven Banarasi silk with a zari border and a contrast blouse piece, packed in a keepsake box.",
    highlights: ["Handwoven", "Zari border", "Unstitched blouse piece", "Gift box"],
    specs: { Fabric: "Silk blend", Length: "5.5m + 0.8m blouse", Work: "Zari", Occasion: "Wedding" },
    images: [img("photo-1610030469983-98e550d6193c"), img("photo-1583394293214-28ded15ee548"), img("photo-1594463750939-ebb28c3f7f75")],
    variantAxes: ["color"],
    variants: axis("BANSAR", "color", ["Rani Pink", "Royal Blue", "Bottle Green"], 5999, 9999, [12, 8, 3]),
    tags: ["saree", "silk", "wedding"],
    isFeatured: true,
  },
  {
    title: "Anarkali Kurta with Dupatta",
    brand: "Roohani",
    category: "womens-ethnic",
    description: "A flared Anarkali in soft rayon with gota detailing and a matching chiffon dupatta.",
    highlights: ["Gota detailing", "Flared silhouette", "Includes dupatta"],
    specs: { Fabric: "Rayon", Length: "Calf length", Set: "Kurta + dupatta" },
    images: [img("photo-1610652492500-ded49ceeb378"), img("photo-1610030469983-98e550d6193c")],
    variantAxes: ["color", "size"],
    variants: matrix("ANARK", [["color", ["Coral", "Teal"]], ["size", SIZES]], 2199, 3999, stock),
    tags: ["kurta", "anarkali", "festive"],
  },
  {
    title: "Block-print Straight Kurta",
    brand: "Sundara",
    category: "womens-ethnic",
    description: "Hand block-printed in Bagru on breathable cotton for everyday wear.",
    highlights: ["Hand block-printed", "100% cotton", "Side slits"],
    specs: { Fabric: "Cotton", Length: "Knee length", Print: "Bagru block print" },
    images: [img("photo-1622470953794-aa9c70b0fb9d"), img("photo-1583744946564-b52ac1c389c8")],
    variantAxes: ["size"],
    variants: axis("BLKKUR", "size", SIZES, 1299, 1999, [25, 30, 20, 10]),
    tags: ["kurta", "cotton", "everyday"],
  },
  {
    title: "Ribbed Knit Crop Top",
    brand: "Mira",
    category: "womens-tops",
    description: "A stretchy ribbed knit that pairs with everything from high-waist jeans to skirts.",
    highlights: ["Ribbed knit", "Square neck", "Stretch fit"],
    specs: { Fabric: "Cotton-elastane", Fit: "Slim", Sleeve: "Sleeveless" },
    images: [img("photo-1564257631407-4deb1f99d992"), img("photo-1618244972963-dbee1a7edc95")],
    variantAxes: ["color", "size"],
    variants: matrix("RIBCRP", [["color", ["Cream", "Rust", "Black"]], ["size", ["S", "M", "L"]]], 799, 1299, stock),
    tags: ["top", "knit"],
  },
  {
    title: "Oversized Poplin Shirt",
    brand: "Loom & Co",
    category: "womens-tops",
    description: "Crisp cotton poplin with a relaxed drape, deep cuffs and a curved hem.",
    highlights: ["Cotton poplin", "Relaxed fit", "Curved hem"],
    specs: { Fabric: "100% cotton", Fit: "Oversized", Sleeve: "Full" },
    images: [img("photo-1598554747436-c9293d6a588f"), img("photo-1594633312681-425c7b97ccd1")],
    variantAxes: ["color", "size"],
    variants: matrix("POPSHT", [["color", ["White", "Powder Blue"]], ["size", SIZES]], 1499, 2499, stock),
    tags: ["shirt", "workwear"],
  },
  {
    title: "Silk Scarf — Marigold Garden",
    brand: "Sundara",
    category: "womens-tops",
    description: "A 90cm square of mulberry silk twill with hand-rolled edges and an original marigold print.",
    highlights: ["Mulberry silk twill", "Hand-rolled edges", "90 x 90 cm"],
    specs: { Fabric: "100% silk", Size: "90 x 90 cm" },
    images: [img("photo-1601924994987-69e26d50dc26"), img("photo-1584030373081-f37b7bb4fa8e")],
    variantAxes: [],
    variants: single("SCARFMG", 1899, 2999, 15),
    tags: ["scarf", "silk", "gift"],
  },
];
