import { axis, img, matrix, SHOE_SIZES, type SeedProduct } from "./helpers";

const stock = ({ size }: Record<string, string>) => (size === "UK 10" ? 5 : 16);

export const footwear: SeedProduct[] = [
  {
    title: "Court Classic Leather Sneakers",
    brand: "Stride",
    category: "sneakers",
    description: "Full-grain leather uppers on a cupsole, with a padded collar and a silhouette that goes with every trouser you own.",
    highlights: ["Full-grain leather", "Cupsole construction", "Padded collar", "Replaceable insole"],
    specs: { Upper: "Full-grain leather", Sole: "Rubber cupsole", Closure: "Lace-up", Origin: "India" },
    images: [img("photo-1600185365926-3a2ce3cdb9eb"), img("photo-1549298916-b41d501d3772"), img("photo-1560769629-975ec94e6a86")],
    variantAxes: ["color", "size"],
    variants: matrix("COURT", [["color", ["White", "Off-white/Green"]], ["size", SHOE_SIZES]], 3499, 5499, stock),
    tags: ["sneakers", "leather", "bestseller"],
    isFeatured: true,
  },
  {
    title: "Retro Runner Suede Sneakers",
    brand: "Stride",
    category: "sneakers",
    description: "A 70s-inspired runner in suede and nylon with a gum sole and a cushioned EVA midsole.",
    highlights: ["Suede + nylon upper", "Gum rubber sole", "EVA cushioning"],
    specs: { Upper: "Suede, nylon", Sole: "Gum rubber", Closure: "Lace-up" },
    images: [img("photo-1542291026-7eec264c27ff"), img("photo-1595950653106-6c9ebd614d3a")],
    variantAxes: ["color", "size"],
    variants: matrix("RETRUN", [["color", ["Burgundy", "Navy", "Mustard"]], ["size", SHOE_SIZES]], 2999, 4999, stock),
    tags: ["sneakers", "retro"],
    isDeal: true,
  },
  {
    title: "Canvas Slip-on Sneakers",
    brand: "Loom & Co",
    category: "sneakers",
    description: "Lightweight canvas slip-ons with elastic gores and a vulcanised sole.",
    highlights: ["Canvas upper", "Vulcanised sole", "Slip-on"],
    specs: { Upper: "Canvas", Sole: "Vulcanised rubber" },
    images: [img("photo-1525966222134-fcfa99b8ae77"), img("photo-1603808033192-082d6919d3e1")],
    variantAxes: ["color", "size"],
    variants: matrix("CANVAS", [["color", ["Black", "Natural"]], ["size", SHOE_SIZES]], 1299, 1999, stock),
    tags: ["slip-on", "casual"],
  },
  {
    title: "Velocity 3 Running Shoes",
    brand: "Kinetic",
    category: "sports-shoes",
    description: "A daily trainer with a nitrogen-infused foam midsole, engineered mesh and a 8mm drop for smooth transitions.",
    highlights: ["Nitrogen-infused foam", "Engineered mesh upper", "8mm drop", "265g (UK 9)"],
    specs: { Weight: "265g", Drop: "8mm", Surface: "Road", Cushioning: "High" },
    images: [img("photo-1606107557195-0e29a4b5b4aa"), img("photo-1539185441755-769473a23570"), img("photo-1556906781-9a412961c28c")],
    variantAxes: ["color", "size"],
    variants: matrix("VELO3", [["color", ["Volt", "Black/Coral"]], ["size", SHOE_SIZES]], 4999, 7999, stock),
    tags: ["running", "shoes", "bestseller"],
    isFeatured: true,
  },
  {
    title: "Trail Grip Hiking Shoes",
    brand: "Kinetic",
    category: "sports-shoes",
    description: "Aggressive 5mm lugs, a rock plate and a waterproof membrane for muddy monsoon trails.",
    highlights: ["5mm lugs", "Waterproof membrane", "Rock plate", "Toe cap"],
    specs: { Surface: "Trail", Waterproof: "Yes", Weight: "310g" },
    images: [img("photo-1520639888713-7851133b1ed0"), img("photo-1606107557195-0e29a4b5b4aa")],
    variantAxes: ["size"],
    variants: axis("TRAIL", "size", SHOE_SIZES, 5499, 8499, [10, 12, 12, 4]),
    tags: ["hiking", "trail"],
  },
  {
    title: "Flex Training Shoes",
    brand: "Kinetic",
    category: "sports-shoes",
    description: "A flat, stable platform for lifting with a flexible forefoot for HIIT and box jumps.",
    highlights: ["Stable heel", "Flexible forefoot", "Breathable knit"],
    specs: { Surface: "Gym", Drop: "4mm" },
    images: [img("photo-1608231387042-66d1773070a5"), img("photo-1595950653106-6c9ebd614d3a")],
    variantAxes: ["color", "size"],
    variants: matrix("FLEXTR", [["color", ["Black", "Grey"]], ["size", SHOE_SIZES]], 3799, 5999, stock),
    tags: ["training", "gym"],
  },
  {
    title: "Cork Footbed Sandals",
    brand: "Sundara",
    category: "sandals-boots",
    description: "Contoured cork footbeds that mould to your feet, with adjustable leather straps.",
    highlights: ["Contoured cork footbed", "Adjustable straps", "EVA outsole"],
    specs: { Footbed: "Cork-latex", Straps: "Leather", Sole: "EVA" },
    images: [img("photo-1603487742131-4160ec999306"), img("photo-1562273138-f46be4ebdf33")],
    variantAxes: ["color", "size"],
    variants: matrix("CORKSD", [["color", ["Tan", "Black"]], ["size", SHOE_SIZES]], 2299, 3499, stock),
    tags: ["sandals", "summer"],
  },
  {
    title: "Chelsea Leather Boots",
    brand: "Stride",
    category: "sandals-boots",
    description: "Goodyear-welted Chelsea boots in pull-up leather that ages beautifully.",
    highlights: ["Goodyear welted", "Pull-up leather", "Elastic side gores", "Resoleable"],
    specs: { Upper: "Pull-up leather", Construction: "Goodyear welt", Sole: "Rubber" },
    images: [img("photo-1608256246200-53e635b5b65f"), img("photo-1638247025967-b4e38f787b76")],
    variantAxes: ["color", "size"],
    variants: matrix("CHELSEA", [["color", ["Tan", "Dark Brown"]], ["size", SHOE_SIZES]], 5999, 8999, stock),
    tags: ["boots", "leather"],
  },
];
