import { axis, img, single, type SeedProduct } from "./helpers";

export const homeKitchen: SeedProduct[] = [
  {
    title: "Brewmaster Drip Coffee Maker",
    brand: "Hearth",
    category: "appliances",
    description: "A 1.2L programmable drip brewer with a thermal carafe that keeps coffee hot for four hours without cooking it.",
    highlights: ["1.2L thermal carafe", "24h programmable", "Bloom pre-infusion", "Reusable filter"],
    specs: { Capacity: "1.2L (8 cups)", Power: "1000W", Carafe: "Stainless thermal", Warranty: "2 years" },
    images: [img("photo-1517668808822-9ebb02f2a0e6"), img("photo-1495474472287-4d71bcdd2085")],
    variantAxes: [],
    variants: single("BREWDRP", 5499, 7999, 22),
    tags: ["coffee", "appliance", "kitchen"],
    isFeatured: true,
  },
  {
    title: "Vortex Pro Blender",
    brand: "Hearth",
    category: "appliances",
    description: "A 1400W blender with a hardened steel blade that crushes ice, nuts and frozen fruit into silk.",
    highlights: ["1400W motor", "2L BPA-free jar", "6 presets", "Self-cleaning"],
    specs: { Power: "1400W", Jar: "2L Tritan", Speeds: "10 + pulse" },
    images: [img("photo-1570222094114-d054a817e56b"), img("photo-1585515320310-259814833e62")],
    variantAxes: ["color"],
    variants: axis("VORTEX", "color", ["Graphite", "Cream"], 6999, 9999, [15, 10]),
    tags: ["blender", "kitchen"],
  },
  {
    title: "Tri-ply Stainless Cookware Set",
    brand: "Hearth",
    category: "appliances",
    description: "A 5-piece tri-ply set (fry pan, saucepan, kadai, stockpot, lids) that heats evenly on induction and gas.",
    highlights: ["Tri-ply construction", "Induction compatible", "Riveted handles", "Oven safe to 250°C"],
    specs: { Material: "Stainless steel, aluminium core", Pieces: "5", Compatibility: "Gas, induction, oven" },
    images: [img("photo-1556909114-f6e7ad7d3136"), img("photo-1556910103-1c02745aae4d")],
    variantAxes: [],
    variants: single("TRIPLY5", 8999, 13999, 9),
    tags: ["cookware", "kitchen"],
    isDeal: true,
  },
  {
    title: "Rapid Boil Electric Kettle",
    brand: "Hearth",
    category: "appliances",
    description: "A 1.7L glass kettle with temperature presets for green tea, pour-over and rolling boil.",
    highlights: ["1.7L borosilicate glass", "5 temperature presets", "Keep-warm mode"],
    specs: { Capacity: "1.7L", Power: "1500W" },
    images: [img("photo-1594213114663-d94db9b17125"), img("photo-1517668808822-9ebb02f2a0e6")],
    variantAxes: [],
    variants: single("KETTLE", 2499, 3499, 40),
    tags: ["kettle", "kitchen"],
  },
  {
    title: "Arc Floor Lamp",
    brand: "Nook",
    category: "decor",
    description: "A sweeping arc lamp with a marble base and a linen drum shade that pools warm light over a sofa or reading chair.",
    highlights: ["Marble base", "Linen drum shade", "Dimmable LED bulb included", "1.9m reach"],
    specs: { Height: "200cm", Base: "Marble", Bulb: "E27 LED (included)" },
    images: [img("photo-1507473885765-e6ed057f782c"), img("photo-1513506003901-1e6a229e2d15")],
    variantAxes: ["finish"],
    variants: axis("ARCLMP", "finish", ["Brass", "Matte Black"], 7499, 10999, [8, 11]),
    tags: ["lamp", "lighting", "decor"],
    isFeatured: true,
  },
  {
    title: "Terracotta Planter Trio",
    brand: "Nook",
    category: "decor",
    description: "Three hand-thrown terracotta planters with drainage and saucers, in graduated sizes.",
    highlights: ["Hand-thrown", "Drainage + saucers", "Set of 3"],
    specs: { Material: "Terracotta", Sizes: "12, 16, 20 cm" },
    images: [img("photo-1485955900006-10f4d324d411"), img("photo-1463320726281-696a485928c7")],
    variantAxes: [],
    variants: single("PLANTR3", 1499, 2299, 30),
    tags: ["planter", "decor", "plants"],
  },
  {
    title: "Soy Candle — Cedar & Cardamom",
    brand: "Nook",
    category: "decor",
    description: "A 220g soy-wax candle with a cotton wick and 45 hours of slow-burning, spiced warmth.",
    highlights: ["Soy wax", "45h burn time", "Reusable glass vessel"],
    specs: { Weight: "220g", Burn: "45 hours", Wick: "Cotton" },
    images: [img("photo-1602143407151-7111542de6e8"), img("photo-1603006905003-be475563bc59")],
    variantAxes: ["scent"],
    variants: axis("CANDLE", "scent", ["Cedar & Cardamom", "Fig & Vetiver", "Sea Salt"], 899, 1299, [40, 40, 12]),
    tags: ["candle", "gift", "decor"],
  },
  {
    title: "Percale Cotton Bedsheet Set",
    brand: "Sleepwell Studio",
    category: "bedding",
    description: "Crisp 300-thread-count long-staple cotton percale, woven for people who run hot.",
    highlights: ["300 TC percale", "Long-staple cotton", "Deep-pocket fitted sheet", "2 pillowcases"],
    specs: { Fabric: "100% long-staple cotton", Weave: "Percale", Includes: "Fitted sheet, 2 pillowcases" },
    images: [img("photo-1522771739844-6a9f6d5f14af"), img("photo-1616594039964-ae9021a400a0")],
    variantAxes: ["size", "color"],
    variants: [
      ...axis("PERCQ", "color", ["White", "Sage", "Clay"], 2999, 4499, [20, 15, 10]).map((v) => ({ ...v, attributes: { size: "Queen", ...v.attributes }, sku: `${v.sku}-QN` })),
      ...axis("PERCK", "color", ["White", "Sage", "Clay"], 3499, 4999, [15, 10, 6]).map((v) => ({ ...v, attributes: { size: "King", ...v.attributes }, sku: `${v.sku}-KG` })),
    ],
    tags: ["bedsheet", "cotton", "bedding"],
  },
  {
    title: "Cloud Down-alternative Comforter",
    brand: "Sleepwell Studio",
    category: "bedding",
    description: "A lofty microfibre comforter with baffle-box stitching so the fill never bunches.",
    highlights: ["Baffle-box stitching", "Hypoallergenic fill", "Machine washable"],
    specs: { Fill: "Microfibre", Shell: "Cotton", Weight: "All-season" },
    images: [img("photo-1631049307264-da0ec9d70304"), img("photo-1522771739844-6a9f6d5f14af")],
    variantAxes: ["size"],
    variants: axis("CLOUDCF", "size", ["Single", "Queen", "King"], 3499, 5499, [12, 18, 10], 800),
    tags: ["comforter", "bedding"],
  },
];
